import turtle
ws = turtle.Screen()
flagTurtle = turtle.Turtle()
flagTurtle.penup()
flagTurtle.goto(-180,60)
### Recuadro Verde
flagTurtle.pendown()
flagTurtle.begin_fill()
flagTurtle.fillcolor("green")
flagTurtle.left(90)
flagTurtle.fd(90)
flagTurtle.rt(90)
flagTurtle.fd(400)
flagTurtle.rt(90)
flagTurtle.fd(90)
flagTurtle.rt(90)
flagTurtle.fd(400)
flagTurtle.end_fill()
## Segundo Rectangulo
flagTurtle.pencolor("black")
flagTurtle.lt(90)
flagTurtle.fd(90)
flagTurtle.lt(90)
flagTurtle.fd(400)
flagTurtle.lt(90)
flagTurtle.fd(90)
flagTurtle.lt(90)
flagTurtle.fd(400)
flagTurtle.lt(90)
flagTurtle.fd(90)
##Tercer Rectangulo
flagTurtle.begin_fill()
flagTurtle.fillcolor("red")
flagTurtle.fd(90)
flagTurtle.lt(90)
flagTurtle.fd(400)
flagTurtle.lt(90)
flagTurtle.fd(90)
flagTurtle.lt(90)
flagTurtle.fd(400)
flagTurtle.end_fill()
##Center
flagTurtle.penup()
flagTurtle.goto(23,32)
flagTurtle.pendown()
flagTurtle.begin_fill()
flagTurtle.fillcolor("black")
flagTurtle.circle(20)
flagTurtle.end_fill()
##
turtle.done()